---
apiversion: application.tsb.tetrate.io/v2
kind: Application
metadata:
  organization: tetrate
  tenant: tetrate
  name: fortune
spec:
  displayName: Fortune
  description: Fortune application
  workspace: organizations/tetrate/tenants/tetrate/workspaces/fortune-workspace
---
apiversion: application.tsb.tetrate.io/v2
kind: API
metadata:
  organization: tetrate
  tenant: tetrate
  application: fortune
  name: fortune-api
spec:
  description: Fortune OpenAPI
  workloadSelector:
    namespace: fortune
    labels:
      app: fortune-gateway
  openapi: |
    openapi: 3.0.1
    info:
      title: OpenAPI definition
      version: v1
      x-tsb-service: fortune-api.fortune
    servers:
    - url: https://fortune.cloud.zwickey.net
      x-tsb-tls:
        mode: SIMPLE
        secretName: fortune-certs
    paths:            
      /ui:
        get:
          x-tsb-service: fortune-ui.fortune
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Fortune'
      /fortune:
        get:
          tags:
          - backend-controller
          operationId: random
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Fortune'
        put:
          tags:
          - backend-controller
          operationId: save
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Fortune'
            required: true
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Fortune'
      /kill:
        get:
          tags:
          - backend-controller
          operationId: kill
          responses:
            "200":
              description: OK
      /fortunes:
        get:
          tags:
          - backend-controller
          operationId: all
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Fortune'
      /fortune/{id}:
        get:
          tags:
          - backend-controller
          operationId: get
          parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
              format: int64
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    $ref: '#/components/schemas/Fortune'
      /clear:
        delete:
          tags:
          - backend-controller
          operationId: clear
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/Fortune'
    components:
      schemas:
        Fortune:
          type: object
          properties:
            id:
              type: integer
              format: int64
            text:
              type: string
