spring:
  application:
    name: fortune
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: "/ui"
springdoc:
  api-docs:
    path: '/openapi'
  swagger-ui:
    path: '/api-docs'
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
---
spring:
  profiles: cloud
