#!/bin/bash

set -xe

pwd
env

cf api $CF_API --skip-ssl-validation

cf login -u $CF_USER -p $CF_PWD -o "$CF_ORG" -s "$CF_SPACE"

cf services

export SERVICE_FOUND=$(cf service "$CF_SERVICE_NAME" | grep "FAILED")
if [[ $SERVICE_FOUND = *FAILED*  ]]; then
  echo "Service hasn't been created"
  cf create-service $CF_SERVICE_MKT $CF_SERVICE_PLAN $CF_SERVICE_NAME -c $CF_SERVICE_COMMAND
else
  echo "Service found"
fi

export STATUS=$(cf service "$CF_SERVICE_NAME" | grep "create succeeded")
until [[ $STATUS = *succeeded* ]]; do
  export CURR=$(cf service "$CF_SERVICE_NAME" | grep "status:")
  echo "Service creation $CURR"
  echo "Waiting 10 seconds..."
  sleep 10
  export STATUS=$(cf service "$CF_SERVICE_NAME" | grep "create succeeded")
done

echo "Service creation finished"